[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
donation_dapp = "yttwzEwuo6ov2pdJbHYn3FAGzXN4ZYxPe3x1KqB6NBm"

[programs.devnet]
donation_dapp = "yttwzEwuo6ov2pdJbHYn3FAGzXN4ZYxPe3x1KqB6NBm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
